# 2d distance to boundary
SYSTEM:
  NUM_GPUS: 4
  NUM_CPUS: 4
MODEL:
  ARCHITECTURE: 'unet_residual_3d'
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  IN_PLANES: 1
  OUT_PLANES: 10
  LOSS_OPTION: [['WeightedBCE']]
  LOSS_WEIGHT: [[1.0]]
  TARGET_OPT: ['5-10']
  WEIGHT_OPT: [['1']]
DATASET:
  IMAGE_NAME: 'im_train.json'
  LABEL_NAME: 'mito_train.json'
  INPUT_PATH: '/n/home00/qshen/new_code/pytorch_connectomics/configs/'
  OUTPUT_PATH: '/n/pfister_lab2/Lab/qijia/checkpoint/rat/D/'
  PAD_SIZE: [16, 128, 128]
  DO_CHUNK_TITLE: 1
  DATA_CHUNK_NUM: [2, 2, 2]
  DATA_CHUNK_ITER: 2500
  LABEL_EROSION: 1
AUGMENTOR:
AUGMENTOR:
  ROTATE:
    ENABLED: False
  RESCALE:
    ENABLED: False
  FLIP:
    ENABLED: False
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: False
  MISSINGPARTS:
    ENABLED: False
  MISSINGSECTION:
    ENABLED: False
  MISALIGNMENT:
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  CUTNOISE:
    ENABLED: False
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 1e-03
  ITERATION_STEP: 1
  ITERATION_SAVE: 2500
  ITERATION_TOTAL: 200000
  SAMPLES_PER_BATCH: 4
INFERENCE:
  INPUT_SIZE: [32, 256, 256]
  OUTPUT_SIZE: [32, 256, 256]
  IMAGE_NAME: 'im_train.json'
  OUTPUT_PATH: 'outputs/MitoEM_R_BC/test/'
  OUTPUT_NAME: 'result'
  PAD_SIZE: [16, 128, 128]
  AUG_MODE: 'mean'
  AUG_NUM: 4
  STRIDE: [16, 128, 128]
  SAMPLES_PER_BATCH: 16